[
  {
    user_name: "OhHenryHeiress",
    first_name: "Sue Ellen",
    last_name: "Mischke",
    email: "OHHSM@email.com",
    password: "password12345",
    posts: [],
    comments: [],
  },
  {
    user_name: "TheVirgin",
    first_name: "Maria",
    last_name: "Penny",
    email: "TVMP@email.com",
    password: "password12345",
    posts: [],
    comments: [],
  },
  {
    user_name: "JerryIsVerryBadMan",
    first_name: "Babu",
    last_name: "Bhatt",
    email: "VBMBB@email.com",
    password: "password12345",
    posts: [],
    comments: [],
  },
  {
    user_name: "FeelsLikeAnArbysNight",
    first_name: "David",
    last_name: "Puddy",
    email: "FLAANDP@email.com",
    password: "password12345",
    posts: [],
    comments: [],
  },
];
